<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RumahSakit;

class RumahSakitsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rumahsakits1=RumahSakit::create([
            'nama_rumah_sakit' => 'RS Persahabatan',
            'alamat' => 'Jalan Persahabatan Raya No.1 Kel.Pisangan Timur, Kec.Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 10,
            'no_telepon' => '4891708',
            'no_fax' => '4711222',
            'email' => 'info@rsuppersahabatan.co.id',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'A',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 1,
            'jenislayanan_id' => 1,
            'tempattidur_id' => 1,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits2=RumahSakit::create([
            'nama_rumah_sakit' => 'RS Pengayoman Cipinang',
            'alamat' => 'Jl Raya Bekasi Timur No 170 B Cipinang',
            'kecamatan_id' => 1,
            'kelurahan_id' => 11,
            'no_telepon' => '33153700',
            'no_fax' => '85914558',
            'email' => 'rspengayoman.dki@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Belum Akreditasi',
            'kepemilikan_id' => 1,
            'jenislayanan_id' => 4,
            'tempattidur_id' => 2,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits3=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. OMNI PULOMAS',
            'alamat' => 'Jalan. Pulomas Barat VI No.20, Kel. Kayu Putih, Kec. Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 7,
            'no_telepon' => '472 27 19',
            'no_fax' => '4718081',
            'email' => '',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 3,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits4=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. MEDIROS ',
            'alamat' => 'Jl. Perintis Kemerdekaan  Kav.149, Kel.Pulogadung, Kec. Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 13,
            'no_telepon' => '472 13 36',
            'no_fax' => '472 13 36',
            'email' => 'medrecmediros@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 4,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits5=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. COLUMBIA ASIA ',
            'alamat' => 'Jalan Kayu Putih, Kel.Kayu Putih, Kec.Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 7,
            'no_telepon' => '47883195',
            'no_fax' => '29559477',
            'email' => 'medicalrecord.pulomas@columbiaasia.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 5,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits6=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. YADIKA',
            'alamat' => 'Jalan Pahlawan Revolusi No.57, Kel. Pondok Bambu, Kec. Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 22,
            'no_telepon' => '866 009 40',
            'no_fax' => '8613332',
            'email' => 'rsyadika@yahoo.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 6,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits7=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. KARTIKA PULO MAS',
            'alamat' => 'Jalan Pulomas Timur No.1, Kel. Kayu Putih, Kec.Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 7,
            'no_telepon' => '471 49 76',
            'no_fax' => '472 34 02',
            'email' => 'yayasankartikapulomas@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 7,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits8=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. ANTAM MEDIKA',
            'alamat' => 'Jl. Pemuda Raya No.1A Kec. Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 12,
            'no_telepon' => '29378939 ',
            'no_fax' => '29378941',
            'email' => 'sekretaris@antam.co.id',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 8,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits9=RumahSakit::create([
            'nama_rumah_sakit' => 'RS  DHARMA NUGRAHA ',
            'alamat' => 'Jl. Balai Pustaka Baru no. 19 Rawamangun jakarta Timur',
            'kecamatan_id' => 1,
            'kelurahan_id' => 9,
            'no_telepon' => '470 74 34',
            'no_fax' => '',
            'email' => '',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Belum Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 9,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits10=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA. ALVERNIA AGUSTA',
            'alamat' => 'Jalan Pemuda No.80, Kelurahan Jati, Kec.Pulogadung',
            'kecamatan_id' => 1,
            'kelurahan_id' => 8,
            'no_telepon' => '470 52 66',
            'no_fax' => '470 44 74',
            'email' => 'alvernia_agusta@yahoo.co.id',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Belum Akreditasi',
            'kepemilikan_id' => 7,
            'jenislayanan_id' => 5,
            'tempattidur_id' => 10,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits11=RumahSakit::create([
            'nama_rumah_sakit' => 'RS Khusus Bedah Rawamangun',
            'alamat' => 'jl. Balai Pustaka Raya No. 29 - 31 Rawamangun,  Jakarta Timur',
            'kecamatan_id' => 1,
            'kelurahan_id' => 9,
            'no_telepon' => '489 35 31',
            'no_fax' => '4710918',
            'email' => 'rs.rawamangun@gmail.com',
            'jenis_rs' => 'Khusus Bedah',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 6,
            'jenislayanan_id' => 6,
            'tempattidur_id' => 11,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits12=RumahSakit::create([
            'nama_rumah_sakit' => 'RS Khusus MATA SMEC',
            'alamat' => 'Jl. Pemuda No. 36, RT05/RW 03 Rawamangun',
            'kecamatan_id' => 1,
            'kelurahan_id' => 9,
            'no_telepon' => '4714848',
            'no_fax' => '',
            'email' => 'jakarta.rsmatasmec.com',
            'jenis_rs' => 'Khusus Mata',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 6,
            'jenislayanan_id' => 17,
            'tempattidur_id' => 12,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits13=RumahSakit::create([
            'nama_rumah_sakit' => 'RSK. Pusat Otak Nasional ',
            'alamat' => 'Jalan MT. Haryono Rt.001/06 Kel.Cawang Kec.Kramat Jati',
            'kecamatan_id' => 2,
            'kelurahan_id' => 34,
            'no_telepon' => '29373377',
            'no_fax' => '29373445',
            'email' => 'rspotakn@gmail.com',
            'jenis_rs' => 'Khusus Otak',
            'tipe_rs' => 'A Khusus',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 1,
            'jenislayanan_id' => 7,
            'tempattidur_id' => 13,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits14=RumahSakit::create([
            'nama_rumah_sakit' => 'RSUD. BUDHI ASIH',
            'alamat' => 'Jl. Dewi Sartika No.200, Kel. Cawang, Kec.Kramat Jati',
            'kecamatan_id' => 2,
            'kelurahan_id' => 34,
            'no_telepon' => '808 78 559',
            'no_fax' => '8009157',
            'email' => 'rsudbudhiasih200@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 8,
            'tempattidur_id' => 14,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits15=RumahSakit::create([
            'nama_rumah_sakit' => 'RSUD  Type D Kramat Jati',
            'alamat' => 'Jl Raya Inpres No 48 Kel Tengah Kramat Jati',
            'kecamatan_id' => 2,
            'kelurahan_id' => 32,
            'no_telepon' => '87791352',
            'no_fax' => '87793604',
            'email' => 'rsukramatjati@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'D',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 8,
            'tempattidur_id' => 15,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits16=RumahSakit::create([
            'nama_rumah_sakit' => 'RS.Bhayangkara Tk.1  R.Said Soekamto',
            'alamat' => 'Jalan Raya RS. Polri Kel. Kramat Jati, Kec.Kramat Jati,  Jakarta Timur',
            'kecamatan_id' => 2,
            'kelurahan_id' => 29,
            'no_telepon' => '809 32 88',
            'no_fax' => '8095310',
            'email' => 'bidyanmedwat.rssukanto@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'A',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 10,
            'tempattidur_id' => 16,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits17=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. Pusdikkes Kodiklat TNI-AD',
            'alamat' => 'Jalan Raya Bogor, Kel. Kramat Jati, Kec.Kramat Jati',
            'kecamatan_id' => 2,
            'kelurahan_id' => 29,
            'no_telepon' => '808 83 704',
            'no_fax' => '',
            'email' => '',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 4,
            'jenislayanan_id' => 11,
            'tempattidur_id' => 17,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits18=RumahSakit::create([
            'nama_rumah_sakit' => 'RSU. UKI ',
            'alamat' => 'Jalan Letjend Sutoyo No.2, Kel. Cawang, Kec.Kramat Jati',
            'kecamatan_id' => 2,
            'kelurahan_id' => 34,
            'no_telepon' => '8092317',
            'no_fax' => '8092445',
            'email' => 'rsuki@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 18,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits19=RumahSakit::create([
            'nama_rumah_sakit' => 'RSU. JIH AL FAUZAN',
            'alamat' => 'Jl. Pedati No.3, Kel. Kampung Tengah, Kec. Kramat Jati',
            'kecamatan_id' => 2,
            'kelurahan_id' => 32,
            'no_telepon' => '87780318',
            'no_fax' => '87780318',
            'email' => 'jakartaislamichospital@yahoo.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'D',
            'status_akreditasi' => 'Belum Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 19,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits20=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA. RESTU KASIH',
            'alamat' => 'Jl. Raya Bogor  No.13A,  Kramat Jati jakarta Timur',
            'kecamatan_id' => 2,
            'kelurahan_id' => 29,
            'no_telepon' => '800 21 66',
            'no_fax' => '808 82 753',
            'email' => 'medrec@rsiarestukasih.com',
            'jenis_rs' => 'Khusus Ibu dan Anak',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 7,
            'jenislayanan_id' => 5,
            'tempattidur_id' => 20,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits21=RumahSakit::create([
            'nama_rumah_sakit' => 'RSKD. Duren Sawit ',
            'alamat' => 'Jalan Duren Sawit Baru No.4, Kel. Duren Sawit, Kec. Duren Sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 23,
            'no_telepon' => '861 55 55',
            'no_fax' => '8628659',
            'email' => 'kesekretariatan.rskdurensawit@gmail.com',
            'jenis_rs' => 'Khusus Jiwa',
            'tipe_rs' => 'A Khusus',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 12,
            'tempattidur_id' => 21,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits22=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. Islam Jakarta Pondok Kopi ',
            'alamat' => 'Jalan Raya Pondok Kopi No.1, Kel. Pondok Kopi, Kec. Duren Sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 25,
            'no_telepon' => '863 06 54',
            'no_fax' => '86604256',
            'email' => 'rsipk@cbn.net.id',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 22,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits23=RumahSakit::create([
            'nama_rumah_sakit' => 'RS dr. Euis ',
            'alamat' => 'Jl. H. Naman no.3 ( Transito ) Pondok Kelapa Jakarta Timur',
            'kecamatan_id' => 3,
            'kelurahan_id' => 24,
            'no_telepon' => '869 05383',
            'no_fax' => '865 6488',
            'email' => '',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Belum Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 23,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits24=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA. BUNDA ALIYAH',
            'alamat' => 'Jl. Pahlawan Revolusi  No.100, Kel. Pondok Bambu, Kec. Duren Sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 22,
            'no_telepon' => '866 025 25',
            'no_fax' => '86615321',
            'email' => 'rsiabundaaliyah@yahoo.com',
            'jenis_rs' => 'Khusus Ibu dan Anak',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 7,
            'jenislayanan_id' => 5,
            'tempattidur_id' => 24,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits25=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA. SAM MARIE BASRA',
            'alamat' => 'Jl. Basuki Rahmat No.31, Kel. Pondok Bambu, Kec. Duren Sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 22,
            'no_telepon' => '86613146',
            'no_fax' => '86613147',
            'email' => 'contact.sambasra@gmail.com',
            'jenis_rs' => 'Khusus Ibu dan Anak',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 7,
            'jenislayanan_id' => 5,
            'tempattidur_id' => 25,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits26=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA. ASTA NUGRAHA',
            'alamat' => 'Jl. Duren Sawit Raya Blok K3 No.1, Kel.Klender Kec. Duren sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 28,
            'no_telepon' => '8615937',
            'no_fax' => '86603953',
            'email' => '',
            'jenis_rs' => 'Khusus Ibu dan Anak',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Belum Akreditasi',
            'kepemilikan_id' => 7,
            'jenislayanan_id' => 5,
            'tempattidur_id' => 26,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits27=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA. SAYYIDAH',
            'alamat' => 'Jalan Taman Malaka Selatan No.6 Kel.Pondok Kelapa Kec.Duren Sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 24,
            'no_telepon' => '8655156',
            'no_fax' => '8649886',
            'email' => 'rsia.sayyidah@yahoo.com',
            'jenis_rs' => 'Khusus Bersalin',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 6,
            'jenislayanan_id' => 113,
            'tempattidur_id' => 27,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits28=RumahSakit::create([
            'nama_rumah_sakit' => 'RSK. Jiwa Islam Klender ',
            'alamat' => 'Jalan Bunga Rampai X, Kel. Pondok Kopi, Kec. Duiren Sawit',
            'kecamatan_id' => 3,
            'kelurahan_id' => 25,
            'no_telepon' => '866 024 02',
            'no_fax' => '86610234',
            'email' => 'rsjiwaislam@yahoo.co.id',
            'jenis_rs' => 'Khusus Jiwa',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 6,
            'jenislayanan_id' => 17,
            'tempattidur_id' => 28,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits29=RumahSakit::create([
            'nama_rumah_sakit' => 'RSAU. Dr. Esnawan Antariksa',
            'alamat' => 'Jalan Merpati No.2, Kel. Halim Perdanakusuma, Kec. Makasar',
            'kecamatan_id' => 4,
            'kelurahan_id' => 38,
            'no_telepon' => '808 819 11',
            'no_fax' => '8098665',
            'email' => 'rsau_esnawan.antariksa@yahoo.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 4,
            'jenislayanan_id' => 14,
            'tempattidur_id' => 29,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits30=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. HAJI  JAKARTA',
            'alamat' => 'Jalan Raya Pondok Gede, Kel. Pinang ranti, Kec.Makasar',
            'kecamatan_id' => 4,
            'kelurahan_id' => 36,
            'no_telepon' => '800 07 03',
            'no_fax' => '80876209',
            'email' => 'info@rshaji-jakarta.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 1,
            'jenislayanan_id' => 1,
            'tempattidur_id' => 30,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits31=RumahSakit::create([
            'nama_rumah_sakit' => 'RS TK.II Moh. Ridwan Meuraksa',
            'alamat' => 'Jl. Taman Mini I, RT04/RW02 Pinang Ranti',
            'kecamatan_id' => 4,
            'kelurahan_id' => 36,
            'no_telepon' => '22819465',
            'no_fax' => '',
            'email' => '',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 4,
            'jenislayanan_id' => 11,
            'tempattidur_id' => 31,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits32=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. HARUM',
            'alamat' => 'Jl. Raya Tarum Barat, Kel. Cipinang Melayu, Kec. Makasar',
            'kecamatan_id' => 4,
            'kelurahan_id' => 39,
            'no_telepon' => '861 72 13',
            'no_fax' => '8601039',
            'email' => 'sekretariat.rsharum@sismamedika.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 32,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits33=RumahSakit::create([
            'nama_rumah_sakit' => 'RSK. Gigi dan Mulut TNI AU',
            'alamat' => 'Jalan Puntodewo No.1 Dirgantara II Rt.001/02 Kel. Halim Kec.Makasar',
            'kecamatan_id' => 4,
            'kelurahan_id' => 38,
            'no_telepon' => '80879256',
            'no_fax' => '80887312',
            'email' => 'urperslakesgilut@gmail.com',
            'jenis_rs' => 'Khusus Gigi dan Mulut',
            'tipe_rs' => 'B Khusus',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 4,
            'jenislayanan_id' => 14,
            'tempattidur_id' => 33,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits34=RumahSakit::create([
            'nama_rumah_sakit' => 'RSKO. CIBUBUR',
            'alamat' => 'Jl. Lapangan Tembak No.74,75  Kel. Cibubur, Kec.Ciracas',
            'kecamatan_id' => 5,
            'kelurahan_id' => 46,
            'no_telepon' => '877 11 968',
            'no_fax' => '87711970',
            'email' => 'rskojakarta@yahoo.co.id',
            'jenis_rs' => 'Khusus Ketergantungan Obat',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 1,
            'jenislayanan_id' => 7,
            'tempattidur_id' => 34,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits35=RumahSakit::create([
            'nama_rumah_sakit' => 'RS Olahraga Nasional',
            'alamat' => 'Jl. Jambore No. 1 , Kel. Cibubur  Kec. Ciracas.',
            'kecamatan_id' => 5,
            'kelurahan_id' => 46,
            'no_telepon' => '5738318',
            'no_fax' => '5731106',
            'email' => 'rsolahragacibubur@gmail.com',
            'jenis_rs' => 'Khusus',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 1,
            'jenislayanan_id' => 16,
            'tempattidur_id' => 35,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits36=RumahSakit::create([
            'nama_rumah_sakit' => 'RSUD Type D Ciracas',
            'alamat' => 'Jl Cibubur No 1 Ciracas',
            'kecamatan_id' => 5,
            'kelurahan_id' => 46,
            'no_telepon' => '8718995',
            'no_fax' => '8718995',
            'email' => 'rsuciracas@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'D',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 8,
            'tempattidur_id' => 36,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits37=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. HARAPAN BUNDA',
            'alamat' => 'Jl. Raya Bogor Km.22 No.44, Kel. Kampung Rambutan, Kec. Ciracas',
            'kecamatan_id' => 5,
            'kelurahan_id' => 50,
            'no_telepon' => '8400257',
            'no_fax' => '87781248',
            'email' => 'keuangan@rsharapanbunda.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 37,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits38=RumahSakit::create([
            'nama_rumah_sakit' => 'RSK. Jantung BINA WALUYA',
            'alamat' => 'Jl. TB. Simatupang No.71, Kel.Susukan, Kec.Ciracas',
            'kecamatan_id' => 5,
            'kelurahan_id' => 49,
            'no_telepon' => '840 46 52',
            'no_fax' => '840 38 69',
            'email' => '',
            'jenis_rs' => 'Khusus Jantung',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 6,
            'jenislayanan_id' => 17,
            'tempattidur_id' => 38,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits39=RumahSakit::create([
            'nama_rumah_sakit' => 'RSUD. PASAR REBO',
            'alamat' => 'Jl. TB. Simatupang No.30, Kel.Gedong, Kec. Pasar Rebo',
            'kecamatan_id' => 6,
            'kelurahan_id' => 42,
            'no_telepon' => '840 11 27',
            'no_fax' => '8411159',
            'email' => 'rsudpasarrebo1@gmailcom',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 8,
            'tempattidur_id' => 39,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits40=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. KESDAM Cijantung',
            'alamat' => 'Jalan Mahoni Cijantung II, Kel. Gedong, Kec. Pasar Rebo',
            'kecamatan_id' => 6,
            'kelurahan_id' => 42,
            'no_telepon' => '87793332',
            'no_fax' => '87793332',
            'email' => 'rskesdamjaya_cijantung@yahoo.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 4,
            'jenislayanan_id' => 11,
            'tempattidur_id' => 40,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits41=RumahSakit::create([
            'nama_rumah_sakit' => 'RSUD Type D MATRAMAN',
            'alamat' => 'Jl. Kebon Kelapa Raya  No.29, Utan Kayu Utara RT01/RW10',
            'kecamatan_id' => 7,
            'kelurahan_id' => 2,
            'no_telepon' => '8581958',
            'no_fax' => '85909055',
            'email' => 'rsukmatraman@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'D',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 9,
            'tempattidur_id' => 41,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits42=RumahSakit::create([
            'nama_rumah_sakit' => 'RSK. JANTUNG JAKARTA',
            'alamat' => 'Jl. Matraman Raya No. 23, Kel. palmeriam Kec. Matraman 13211',
            'kecamatan_id' => 7,
            'kelurahan_id' => 5,
            'no_telepon' => '293 61160-67',
            'no_fax' => '',
            'email' => 'jakartaheartcenter@gmail.com ',
            'jenis_rs' => 'Khusus Jantung',
            'tipe_rs' => 'B Khusus',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 6,
            'jenislayanan_id' => 17,
            'tempattidur_id' => 42,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits43=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. Premier Jatinegara ',
            'alamat' => ' Jalan Raya Jatinegara Timur No.85-87, Kel. Balimester Kec. Jatinegara',
            'kecamatan_id' => 8,
            'kelurahan_id' => 14,
            'no_telepon' => '280 08 88',
            'no_fax' => '2800755',
            'email' => 'sekretaris-rspj@ramsayhealth.co.id',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 43,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits44=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. Hermina Jatinegara ',
            'alamat' => 'Jalan Jatinegara Barat No.126, Kel. Kampung Melayu, Kec. Jatinegara',
            'kecamatan_id' => 8,
            'kelurahan_id' => 15,
            'no_telepon' => '8191223',
            'no_fax' => '8190111',
            'email' => 'jakartaislamichospital@yahoo.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 44,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits45=RumahSakit::create([
            'nama_rumah_sakit' => 'RS. HARAPAN JAYAKARTA',
            'alamat' => 'Jl. Bekasi Timur Raya   No.6, Kel.Jatinegara, Kec. Cakung Jakarta Timur',
            'kecamatan_id' => 9,
            'kelurahan_id' => 62,
            'no_telepon' => '4608886',
            'no_fax' => '4608863',
            'email' => 'info@rshjayakarta.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 3,
            'jenislayanan_id' => 2,
            'tempattidur_id' => 45,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits46=RumahSakit::create([
            'nama_rumah_sakit' => 'RSIA.  RESTI  MULYA',
            'alamat' => 'Jl. Pahlawan Komarudin Raya No.5, Kel. Penggilingan, Kec. Cakung ',
            'kecamatan_id' => 9,
            'kelurahan_id' => 63,
            'no_telepon' => '480 39 36',
            'no_fax' => '48701488',
            'email' => 'rsia_resty_mulya@gmail.com',
            'jenis_rs' => 'Khusus Ibu dan Anak',
            'tipe_rs' => 'C',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 7,
            'jenislayanan_id' => 5,
            'tempattidur_id' => 46,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits47=RumahSakit::create([
            'nama_rumah_sakit' => 'RSU ADHYAKSA',
            'alamat' => 'Jl. Raya   No. 60  Hankam Kel. Ceger  Kec. Cipayung.',
            'kecamatan_id' => 10,
            'kelurahan_id' => 52,
            'no_telepon' => '29462345',
            'no_fax' => '29462370',
            'email' => 'rsia_resty_mulya@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'B',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 8,
            'tempattidur_id' => 47,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);

        $rumahsakits48=RumahSakit::create([
            'nama_rumah_sakit' => 'RSUD Cipayung',
            'alamat' => 'Jl. Mini III RT04 RW 03 Bambu Apus Cipayung 13890',
            'kecamatan_id' => 10,
            'kelurahan_id' => 58,
            'no_telepon' => '85506588',
            'no_fax' => '',
            'email' => 'rsudcipayung@gmail.com',
            'jenis_rs' => 'Umum',
            'tipe_rs' => 'D',
            'status_akreditasi' => 'Sudah Akreditasi',
            'kepemilikan_id' => 2,
            'jenislayanan_id' => 8,
            'tempattidur_id' => 48,
            'latitude' => '',
            'longitude' => '',
            'images' => '',
            'tahun_pendataan' => 2020,
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        ]);
    }
}
